# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T09:02:17+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field


class CheckoutUtilityRequest(BaseModel):
    originDomains: List[str] = Field(
        ...,
        description='The list of origin domains, for which origin keys are requested.',
    )


class CheckoutUtilityResponse(BaseModel):
    originKeys: Optional[Dict[str, str]] = Field(
        None,
        description='The list of origin keys for all requested domains. For each list item, the key is the domain and the value is the origin key.',
    )
